theme: jekyll-theme-hacker
title: YeenDeer softness blog
author: ellietheyeen
description: >-
  Ellie the Yeen is a soft YeenDeer that mweeoops and does programming

include: [".well-known"]
timezone: Europe/Stockholm
paginate: 20
defaultmedia: https://github.com/EllieTheYeen.png

plugins:
  - jekyll-relative-links
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      image: https://github.com/EllieTheYeen.png
      twitter:
        card: "summary"

sharebuttons:
  - name: Tumblr
    base: https://www.tumblr.com/widgets/share/tool
    extra: posttype=link
    url: canonicalUrl
    title: title
    color: '#34465D'
  - name: Twitter
    base: https://twitter.com/intent/tweet
    url: url
    title: text
    color: '#08a0e9'
  - name: Reddit
    base: https://reddit.com/submit
    url: url
    title: title
    color: '#ff4500'
  - name: Facebook
    base: https://www.facebook.com/sharer.php
    url: u
    color: '#4267B2'
  - name: Pinterest
    base: http://pinterest.com/pin/create/link/
    url: url
    title: description
    media: media
    color: '#cc2127'
  - name: Telegram
    base: https://telegram.me/share/url
    url: url
    color: '#27a6e7'
  - name: YCombinator
    base: https://news.ycombinator.com/submitlink
    url: u
    title: t
    color: '#cc5200'
  - name: Instapaper
    base: https://www.instapaper.com/edit
    url: url
    color: '#828181'
  - name: Pinboard
    base: https://pinboard.in/add
    url: url
    color: '#1120ab'
  - name: Pocket
    base: https://getpocket.com/edit
    url: url
    color: '#e0264b'
  - name: GMail
    base: https://mail.google.com/mail/u/0/
    extra: 'fs=1&tf=cm'
    body: body
    color: '#ea4235'
  - name: Blogger
    base: https://www.blogger.com/blog_this.pyra
    body: n
    color: '#ff5722'
  - name: Email
    base: 'mailto:'
    body: body
    title: subject
    color: '#26BF74'
