theme: jekyll-theme-hacker
title: YeenDeer softness blog by Ellie the Yeen
description: >-
  A YeenDeer is soft and mweeoops

plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include: [".well-known"]
